### ISSUE TITLE
Energy Bolt bug

### ISSUE THREAD

**Issue by sweetkristas** [anura-engine/wesnoth2#1]
Currently Energy Bolt is castable on the caster, such that you take damage from your own spell.

**Comment by davewx7** [comment]
The possible_targets field should be changed from unit_targets to
enemy_targets to make it only castable on enemies.

On Thu, Jun 23, 2016 at 12:59 PM, Kristina Simpson <notifications@github.com

**Comment by Vultraz** [comment]
Fixed. Thanks.
